# Generated by Django 4.2.4 on 2023-08-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cimage',
            field=models.ImageField(default='null.jpg', upload_to='data'),
        ),
    ]
