# Generated by Django 4.2.4 on 2023-09-04 05:53

from django.db import migrations, models
import django.db.models.deletion
import userapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(max_length=100, verbose_name=userapp.models.Customer),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.customer')),
            ],
        ),
    ]
