# Generated by Django 4.2.4 on 2023-09-04 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_product'),
        ('userapp', '0003_alter_contacts_name_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='productid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
