# Generated by Django 4.2.4 on 2023-09-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_cart_price_cart_productid_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
