# Generated by Django 4.2.4 on 2023-09-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
