# Generated by Django 4.2.4 on 2023-09-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_checkout_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
