# Generated by Django 4.2.4 on 2023-09-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_cart_quantity_cart_status_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
