# Generated by Django 4.2.4 on 2023-09-15 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_product_stock'),
        ('userapp', '0013_alter_cart_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('productid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.product')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.customer')),
            ],
        ),
    ]
