# Generated by Django 4.2.4 on 2023-09-18 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_product_stock'),
        ('userapp', '0015_buy_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('cartid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.cart')),
                ('productid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.product')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.customer')),
            ],
        ),
    ]
