# Generated by Django 4.2.4 on 2023-09-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_alter_order_cartid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
