# Generated by Django 4.2.4 on 2023-09-19 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0022_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='reset',
            name='userid',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.customer'),
        ),
    ]
